replicaCount: 1

image:
  repository: "ilia0178/prime-checker"
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 9090

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}