replicaCount: 1

image:
  repository: YOUR_DOCKERHUB_USERNAME/prime-checker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 9090

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}