apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-checker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prime-checker
  template:
    metadata:
      labels:
        app: prime-checker
    spec:
      containers:
        - name: prime-checker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9090