apiVersion: v1
kind: Service
metadata:
  name: prime-checker
  labels:
    app: prime-checker
spec:
  type: {{ .Values.service.type }}
  selector:
    app: prime-checker

  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9090