apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prime-checker
spec:
  selector:
    matchLabels:
      app: prime-checker

  endpoints:
    - port: metrics
      path: /metrics
      interval: 5s