name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image locally
        run: docker build -t prime-checker .

      - name: Run container to test binary
        run: docker run --rm prime-checker